project:
  type: website

website:
  title: "António Barros"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
        
  page-footer:
    left: "Copyright 2024 António Barros"
    right: 
      - icon: github
      - href: https://github.com/antoniobarros

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

